import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const browser = await chromium.launch({ channel:'chrome', headless:true });
const page = await browser.newPage({ viewport:{width:1440,height:900} });
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
const report={};
const shot=async name=>{
  // Wait for finite JS transitions; loading loops intentionally remain animated.
  await page.waitForFunction(()=>{
    const r=document.querySelector('#moodle-workspace')?.shadowRoot;
    return r && [...r.querySelectorAll('.overlay,.dialog,.drawer,[data-left-body]>*,[data-bottom-body]>*,.results>*,.tutor-issues>*,.tutor-reveal[open]>*')].every(n=>Number(getComputedStyle(n).opacity)>.99);
  });
  await page.screenshot({path:`.dbg/v5-${name}.png`,animations:'disabled'});
};
try {
  await page.goto('http://10.140.103.120/moodle/mod/programming/submit.php?a=117');
  if(await page.locator('input[type=password]').count()) {
    assert.ok(process.env.MOODLE_USER && process.env.MOODLE_PASSWORD,'Supply test account in environment');
    await page.locator('#username').fill(process.env.MOODLE_USER);
    await page.locator('#password').fill(process.env.MOODLE_PASSWORD);
    await Promise.all([page.waitForURL(url=>!url.pathname.includes('/login/')),page.getByRole('button',{name:'登录',exact:true}).click()]);
    await page.goto('http://10.140.103.120/moodle/mod/programming/submit.php?a=117');
  }
  await page.addScriptTag({content:await readFile('code.user.js','utf8')});
  const ui=page.locator('#moodle-workspace');
  await ui.locator('.cm-content').waitFor();
  await page.screenshot({path:'.dbg/v4-desktop.png'});
  const content=ui.locator('.cm-content');
  let before=await content.innerText();
  await content.click();
  await page.keyboard.press('Control+Home');
  await page.keyboard.type('// keyboard probe');
  await page.keyboard.press('Enter');
  assert.ok((await content.innerText()).startsWith('// keyboard probe\n'));
  await page.keyboard.press('Control+z');
  await page.keyboard.press('Control+z');
  assert.equal(await content.innerText(),before);
  await page.keyboard.press('Tab');
  assert.notEqual(await content.innerText(),before);
  await page.keyboard.press('Control+z');
  assert.equal(await content.innerText(),before);
  report.keyboard='native typing, Enter, undo, Tab passed';
  await page.keyboard.insertText('#include <stdio.h>\n\nint main(void) {\n    int a, b;\n    if (scanf("%d%d", &a, &b) == 2) {\n        printf("%d\\n", a + b);\n    }\n    return 0;\n}\n');
  before=await content.innerText();
  await page.keyboard.press('Control+Space');
  await ui.locator('.cm-tooltip-autocomplete').waitFor();
  await shot('keyboard');
  await page.keyboard.press('Escape');
  await shot('desktop');
  await ui.locator('[data-action=next]').click();
  await ui.locator('h1').filter({hasText:'1.4'}).waitFor();
  assert.ok(!page.url().endsWith('a=117'));
  await content.click();await page.keyboard.press('Control+Home');
  await page.keyboard.type('// isolated draft');
  await ui.locator('[data-action=prev]').click();
  await ui.locator('h1').filter({hasText:'1.3'}).waitFor();
  assert.equal(await content.innerText(),before);
  await ui.locator('[data-action=problems]').click();
  await ui.locator('[data-search]').fill('1.4 ');
  await shot('problems');
  await ui.locator('[data-problem]').first().click();
  await ui.locator('h1').filter({hasText:'1.4'}).waitFor();
  assert.ok((await content.innerText()).startsWith('// isolated draft'));
  await ui.locator('[data-action=prev]').click();
  await ui.locator('h1').filter({hasText:'1.3'}).waitFor();
  report.navigation='previous, next, search, per-problem drafts passed';
  await ui.locator('[data-action=clear]').click();
  await ui.locator('[data-confirm-clear]').click();
  assert.equal(await content.innerText(),'\n');
  await page.keyboard.press('Control+z');
  assert.equal(await content.innerText(),before);
  const splitter=ui.locator('[data-resize=x]');
  const box=await splitter.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+100);
  await page.mouse.down();await page.mouse.move(550,box.y+100);await page.mouse.up();
  assert.ok((await ui.locator('.left').boundingBox()).width<600);
  await splitter.focus();await page.keyboard.press('ArrowRight');
  await shot('resized');
  report.clearAndResize='clear confirmation, native undo, drag and keyboard resize passed';
  await ui.locator('[data-left=history]').click();
  await ui.locator('.history-item').first().waitFor();
  await ui.locator('.history-item').first().click();
  await ui.locator('.history-code').waitFor();
  assert.ok((await ui.locator('.history-code').innerText()).includes('main'));
  await ui.locator('[data-left=description]').click();
  await ui.locator('h1').waitFor();
  report.history='list, read code, return to description passed';
  await ui.locator('[data-action=add-case]').click();
  await ui.locator('[data-test-input]').fill('12 30\n');
  await ui.locator('[data-test-expected]').fill('42\n');
  await ui.locator('[data-action=delete-case]').click();
  assert.equal(await ui.locator('[data-case]').count(),2);
  await ui.locator('[data-action=file]').click();
  await ui.locator('input[type=file]').setInputFiles({name:'probe.c',mimeType:'text/plain',buffer:Buffer.from('int main(){return 0;}')});
  await ui.locator('[data-action=unfile]').click();
  assert.equal(await ui.locator('input[type=file]').evaluate(e=>e.files.length),0);
  report.casesAndFile='add, edit, delete, attach, cancel passed';
  await ui.locator('[data-action=settings]:visible').click();
  await shot('settings');
  assert.equal(await ui.locator('[data-model]').inputValue(),'deepseek-ai/DeepSeek-V4-Pro');
  assert.equal(await ui.locator('[data-model]').getAttribute('readonly'),'');
  await ui.locator('[data-save-settings]').click();
  await ui.locator('[data-action=settings]:visible').click();
  assert.equal(await ui.locator('[data-model]').inputValue(),'deepseek-ai/DeepSeek-V4-Pro');
  await page.keyboard.press('Escape');
  report.settings='save, reopen, Escape passed (no external AI request)';
  if(process.env.MOODLE_SUBMIT==='1') {
    await ui.locator('[data-action=submit]').click();
    await page.waitForFunction(()=>{
      const r=document.querySelector('#moodle-workspace').shadowRoot;
      return !r.querySelector('[data-action=submit]').disabled && r.querySelector('.submission-id');
    },null,{timeout:60000});
    assert.equal(await ui.locator('.results-table tbody tr').count(),4);
    assert.match(await ui.locator('.result-title').innerText(),/4 \/ 4/);
    assert.equal(await ui.locator('.result-warning').count(),0);
    report.submission=`official submission passed 4/4: ${await ui.locator('.submission-id').innerText()}`;
    await shot('submitted');
  }
  await ui.locator('[data-action=refresh-result]').click();
  await ui.locator('.results-table tbody tr').first().waitFor();
  await ui.locator('[data-result="1"]').click();
  assert.ok((await ui.locator('.facts').innerText()).includes('用例 2'));
  await shot('results');
  report.results='existing results table and selected-case details passed';
  await page.setViewportSize({width:390,height:844});
  await shot('mobile-code');
  assert.ok(await ui.locator('[data-action=mobile-description]').isVisible());
  await ui.locator('[data-action=mobile-description]').click();
  assert.ok(await ui.locator('h1').isVisible());
  await shot('mobile-description');
  await page.setViewportSize({width:1024,height:650});
  await shot('compact');
  report.responsive='390, 1024, 1440 layouts captured';
  await page.setViewportSize({width:1440,height:900});
  if(process.env.LIVE_AI==='1'){
    await content.click();await page.keyboard.press('Control+a');
    await page.keyboard.insertText(before.replace('a + b','a - b'));
    await ui.locator('[data-left=tutor]').click();
    await ui.locator('[data-tutor-question]').fill('请引导我检查两数求和的输出问题，不要直接给出完整答案�?);
    await ui.locator('[data-action=ask-tutor]').click();
    await ui.locator('.tutor-explanation,.tutor-error').first().waitFor({timeout:100000});
    assert.equal(await ui.locator('.tutor-error').count(),0,await ui.locator('.tutor-response').innerText());
    assert.ok((await ui.locator('.tutor-explanation').innerText()).length>20);
    assert.equal(await ui.locator('.tutor-composer[open]').count(),0);
    assert.equal(await ui.locator('.tutor-fix[open]').count(),0);
    await shot('tutor-live');
    report.liveAI='specified SiliconFlow model returned a structured tutorial using real Moodle context';
    await content.click();await page.keyboard.press('Control+a');await page.keyboard.insertText(before);
    await ui.locator('[data-left=description]').click();
  }
  // Mock only external providers; Moodle navigation and judging above use the real site.
  let failAI=false,tutorMode='good',tutorContext,releaseTutor,holdPreview=false,releasePreview;
  const tutorAnswer={explanation:'先对照输入和输出，再检�?*运算�?*。\n\n历史提交和当前代码可能不同，请分别判断�?,issues:[{startLine:6,endLine:6,severity:'warning',title:'检查运算表达式',problem:'这一行决定输出的计算方式�?,hint:'题目要求哪一种运算？',suggestion:'将表达式调整为两数相加�?,replacement:'printf("%d\\n", a + b);'}],nextSteps:['手算一组输入，再与程序对照�?]};
  await page.route(/^https:\/\/(?:workspace\.test|api\.siliconflow\.cn)\//,async route=>{
    const request=route.request();
    const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,authorization'};
    if(request.method()==='OPTIONS')return route.fulfill({status:204,headers});
    if(failAI)return route.fulfill({status:401,headers,body:'unauthorized'});
    const data=request.postDataJSON();
    let body;
    if(request.url().endsWith('/run'))body={results:data.tests.map(t=>({stdout:t.expected,stderr:'',time:0.01,memory:1}))};
    else {
      assert.equal(data.model,'deepseek-ai/DeepSeek-V4-Pro');
      const prompt=data.messages.at(-1).content;
      const isTutor=data.messages[0].role==='system';
      if(isTutor){
        tutorContext=JSON.parse(prompt.split('以下 JSON 是本次分析的冻结快照：\n')[1]);
        if(tutorMode==='hold')await new Promise(resolve=>{releaseTutor=resolve;});
      }
      if(!isTutor&&holdPreview)await new Promise(resolve=>{releasePreview=resolve;});
      const answer=isTutor?(tutorMode==='invalid'?'not json':JSON.stringify(tutorAnswer)):prompt.includes('只回�?OK')?'OK':prompt.includes('严格返回 JSON')?'{"tests":[{"input":"1 2\\n","expected":"3\\n"}]}':'/* AI preview */';
      body={choices:[{message:{content:answer}}]};
    }
    await route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify(body)});
  });
  await ui.locator('[data-action=settings]:visible').click();
  await ui.locator('[data-enabled]').check();
  await ui.locator('[data-runner]').fill('https://workspace.test/run');
  await ui.locator('[data-test-connection]').click();
  await ui.locator('[data-connection]').filter({hasText:'连接成功'}).waitFor();
  failAI=true;await ui.locator('[data-test-connection]').click();
  await ui.locator('[data-connection]').filter({hasText:'401'}).waitFor();
  await shot('api-error');failAI=false;
  await ui.locator('[data-save-settings]').click();
  holdPreview=true;
  const unchanged=await content.innerText();
  await ui.locator('[data-action=complete]').click();
  await ui.locator('.overlay .ai-loading').waitFor();
  await shot('completion-loading');
  await ui.locator('.overlay footer [data-close]').click();
  assert.equal(await ui.locator('.overlay').count(),0);
  releasePreview?.();holdPreview=false;
  assert.equal(await content.innerText(),unchanged);
  await content.click();await page.keyboard.press('Control+End');
  await ui.locator('[data-action=complete]').click();
  await ui.locator('[data-apply]').waitFor();
  await shot('ai-preview');
  await ui.locator('[data-apply]').click();
  assert.ok((await content.innerText()).includes('/* AI preview */'));
  await page.keyboard.press('Control+z');
  await ui.locator('[data-bottom=cases]').click();
  await ui.locator('[data-action=generate]').click();
  await ui.locator('[data-add-generated]').click();
  assert.equal(await ui.locator('[data-case]').count(),3);
  await ui.locator('[data-action=run]').click();
  await ui.locator('.result-title').filter({hasText:'3 / 3'}).waitFor();
  report.mockAPIs='connection success/401, completion cancel/preview/apply/undo, generated case preview, custom runner passed';
  await ui.locator('[data-left=tutor]').click();
  if(await ui.locator('.tutor-composer:not([open])').count())await ui.locator('.tutor-composer summary').click();
  await ui.locator('[data-tutor-question]').fill('请先引导，不要直接展示修改方法�?);
  tutorMode='hold';
  await ui.locator('[data-action=ask-tutor]').click();
  await ui.locator('.tutor-response .ai-loading').waitFor();
  await shot('tutor-loading');
  await page.waitForFunction(()=>document.querySelector('#moodle-workspace').shadowRoot.querySelector('.ai-loading strong')?.textContent.includes('对照'));
  while(!releaseTutor)await new Promise(resolve=>setImmediate(resolve));
  releaseTutor();tutorMode='good';
  await ui.locator('.tutor-issue').waitFor();
  assert.equal(tutorContext.publicTests.length,2);
  assert.equal(tutorContext.workspaceTests.length,3);
  assert.equal(tutorContext.submission.cases.length,3);
  assert.ok(tutorContext.submission.cases[0].expected);
  assert.ok(tutorContext.submission.cases[0].actual);
  assert.equal(await ui.locator('.tutor-composer[open]').count(),0);
  assert.equal(await ui.locator('.tutor-fix[open]').count(),0);
  assert.equal(await ui.locator('.fix-content').first().isVisible(),false);
  await shot('tutor');
  await ui.locator('[data-ai-line="0"]').click();
  assert.ok((await ui.locator('[data-cursor]').innerText()).includes('�?6'));
  assert.ok(await ui.locator('.ai-line-warning').count());
  await ui.locator('.tutor-fix summary').first().click();
  assert.equal(await ui.locator('.fix-content').first().isVisible(),true);
  await ui.locator('.fix-content').first().scrollIntoViewIfNeeded();
  await shot('tutor-suggestion');
  await content.click();await page.keyboard.press('Control+End');await page.keyboard.type(' ');
  assert.equal(await ui.locator('[data-ai-line="0"]').isDisabled(),true);
  assert.equal(await ui.locator('.ai-line-warning').count(),0);
  assert.equal(await ui.locator('[data-tutor-stale]').isVisible(),true);
  await page.keyboard.press('Control+z');
  tutorMode='invalid';await ui.locator('[data-action=ask-tutor]').click();
  await ui.locator('.tutor-error').waitFor();
  assert.match(await ui.locator('.tutor-error').innerText(),/JSON/);
  tutorMode='hold';releaseTutor=null;await ui.locator('[data-action=ask-tutor]').click();
  await ui.locator('[data-action=cancel-tutor]').click();
  await ui.locator('[data-action=ask-tutor]').waitFor();
  releaseTutor?.();
  await page.setViewportSize({width:390,height:844});
  await ui.locator('[data-action=mobile-code]').click();
  await ui.locator('[data-action=tutor-diagnose]').click();
  assert.equal(await ui.locator('.tutor-heading').isVisible(),true);
  await shot('tutor-mobile');
  await page.setViewportSize({width:1440,height:900});
  await page.emulateMedia({reducedMotion:'reduce'});
  await ui.locator('[data-left=description]').click();await ui.locator('[data-left=tutor]').click();
  await shot('tutor-reduced-motion');
  report.tutor='context, hidden fixes, line navigation/highlighting, stale-code invalidation, malformed JSON, cancel and reduced-motion passed';
  assert.deepEqual(errors,[]);
  process.stdout.write(JSON.stringify(report,null,2)+'\n');
} catch(error) {
  await page.screenshot({path:'.dbg/v4-test-failure.png'});
  process.stderr.write(JSON.stringify({report,errors,error:error.stack},null,2)+'\n');
  process.exitCode=1;
} finally {await browser.close();}
